In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
# As the above dataset contains sex and smoker columns as a categorical value 
# We need to convert that into numerical value using below one hot encoding method.
dataset=pd.get_dummies(dataset,drop_first=True) # Removing the repeated value column

In [5]:
dataset # Once the categorical columns converted into numerical column values

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']] # separating the input values
dep=dataset['charges'] # separating the output values

In [7]:
# Consolidating the playable parameters probability and also considering the cross validation
# Considering different portions of a data set as a test and traint set
from sklearn.model_selection import GridSearchCV 
from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['mse','mae','friedman_mse'],
'max_features': ['auto','sqrt','log2'],
'splitter':['best','random']} # Giving all possible HTPs
grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose = 3,n_jobs=-1) 
# refit = True means consider the best result model as a result model
# refit = False means consider the last combination model as a result model
# fitting the model for grid search
grid.fit(indep, dep) # Passing whole dataset input and output variable

Fitting 5 folds for each of 18 candidates, totalling 90 fits

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['mse', 'mae', 'friedman_mse'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [8]:
# print best parameter after tuning
print(grid.best_params_)
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

{'criterion': 'friedman_mse', 'max_features': 'auto', 'splitter': 'random'}
The R_score value for best parameter {'criterion': 'friedman_mse', 'max_features': 'auto', 'splitter': 'random'}:

In [9]:
re

{'mean_fit_time': array([0.59655838, 0.06474934, 0.05782366, 0.05010753, 0.04945016,
        0.2232389 , 0.17648354, 0.12910399, 0.08861856, 0.10378251,
        0.09483309, 0.12499661, 0.00937667, 0.00937548, 0.0194418 ,
        0.00479584, 0.00937638, 0.01001058]),
 'std_fit_time': array([8.92114949e-01, 2.23049663e-02, 8.40151852e-03, 7.06210375e-04,
        1.48430240e-03, 3.12128813e-01, 4.97199305e-02, 3.67601366e-02,
        2.77225148e-02, 7.50030263e-02, 1.52952970e-02, 1.25385293e-01,
        7.65601844e-03, 7.65504498e-03, 7.35655973e-03, 6.00825181e-03,
        7.65578457e-03, 8.25524895e-03]),
 'mean_score_time': array([0.00860682, 0.00865026, 0.00299864, 0.00619683, 0.00586662,
        0.00314069, 0.00586214, 0.00693674, 0.01593981, 0.00937471,
        0.01787338, 0.00937519, 0.00625057, 0.00937428, 0.00759587,
        0.01458173, 0.00625124, 0.0074512 ]),
 'std_score_time': array([0.00600465, 0.00610311, 0.00244838, 0.00097741, 0.00306656,
        0.00410312, 0.00587955, 0.01153803, 0.01712662, 0.0124992 ,
        0.01468086, 0.00765481, 0.00765536, 0.00765407, 0.00517028,
        0.00954882, 0.00765617, 0.00702654]),
 'param_criterion': masked_array(data=['mse', 'mse', 'mse', 'mse', 'mse', 'mse', 'mae', 'mae',
                    'mae', 'mae', 'mae', 'mae', 'friedman_mse',
                    'friedman_mse', 'friedman_mse', 'friedman_mse',
                    'friedman_mse', 'friedman_mse'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False],
        fill_value='?',
             dtype=object),
 'param_max_features': masked_array(data=['auto', 'auto', 'sqrt', 'sqrt', 'log2', 'log2', 'auto',
                    'auto', 'sqrt', 'sqrt', 'log2', 'log2', 'auto', 'auto',
                    'sqrt', 'sqrt', 'log2', 'log2'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False],
        fill_value='?',
             dtype=object),
 'param_splitter': masked_array(data=['best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random', 'best', 'random'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False],
        fill_value='?',
             dtype=object),
 'params': [{'criterion': 'mse', 'max_features': 'auto', 'splitter': 'best'},
  {'criterion': 'mse', 'max_features': 'auto', 'splitter': 'random'},
  {'criterion': 'mse', 'max_features': 'sqrt', 'splitter': 'best'},
  {'criterion': 'mse', 'max_features': 'sqrt', 'splitter': 'random'},
  {'criterion': 'mse', 'max_features': 'log2', 'splitter': 'best'},
  {'criterion': 'mse', 'max_features': 'log2', 'splitter': 'random'},
  {'criterion': 'mae', 'max_features': 'auto', 'splitter': 'best'},
  {'criterion': 'mae', 'max_features': 'auto', 'splitter': 'random'},
  {'criterion': 'mae', 'max_features': 'sqrt', 'splitter': 'best'},
  {'criterion': 'mae', 'max_features': 'sqrt', 'splitter': 'random'},
  {'criterion': 'mae', 'max_features': 'log2', 'splitter': 'best'},
  {'criterion': 'mae', 'max_features': 'log2', 'splitter': 'random'},
  {'criterion': 'friedman_mse', 'max_features': 'auto', 'splitter': 'best'},
  {'criterion': 'friedman_mse', 'max_features': 'auto', 'splitter': 'random'},
  {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'splitter': 'best'},
  {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'splitter': 'random'},
  {'criterion': 'friedman_mse', 'max_features': 'log2', 'splitter': 'best'},
  {'criterion': 'friedman_mse', 'max_features': 'log2', 'splitter': 'random'}],
 'split0_test_score': array([0.72684265, 0.69285737, 0.68947935, 0.64142527, 0.80262821,
        0.71989629, 0.72595308, 0.65567782, 0.72522723, 0.67162437,
        0.72652402, 0.58351062, 0.71115199, 0.6858775 , 0.74309562,
        0.68335783, 0.61804339, 0.63930545]),
 'split1_test_score': array([0.61128815, 0.66796459, 0.5361263 , 0.57157085, 0.63802392,
        0.54474484, 0.56524045, 0.62755645, 0.44497286, 0.51418884,
        0.53690863, 0.57978537, 0.65425327, 0.63371795, 0.65035333,
        0.55438899, 0.59830647, 0.53606366]),
 'split2_test_score': array([0.72924685, 0.74250683, 0.7326111 , 0.74951353, 0.73285422,
        0.66260906, 0.71702498, 0.73536494, 0.71012406, 0.70039883,
        0.62756143, 0.73448203, 0.72098431, 0.76321334, 0.73199241,
        0.74014335, 0.72472901, 0.67005347]),
 'split3_test_score': array([0.72916728, 0.70594074, 0.63060891, 0.64288593, 0.6427029 ,
        0.72491016, 0.72343645, 0.73346521, 0.7263836 , 0.66812079,
        0.69606595, 0.71628617, 0.73396252, 0.72115915, 0.69944042,
        0.70631565, 0.62449889, 0.67576383]),
 'split4_test_score': array([0.67097899, 0.6658816 , 0.69438641, 0.61826873, 0.71689928,
        0.68134977, 0.75289796, 0.73262523, 0.67039809, 0.61673893,
        0.73162026, 0.56748704, 0.67531341, 0.7612583 , 0.57081251,
        0.67225074, 0.68073789, 0.67126563]),
 'mean_test_score': array([0.69350478, 0.69503023, 0.65664241, 0.64473286, 0.70662171,
        0.66670202, 0.69691058, 0.69693793, 0.65542117, 0.63421435,
        0.66373606, 0.63631024, 0.6991331 , 0.71304525, 0.67913886,
        0.67129131, 0.64926313, 0.63849041]),
 'std_test_score': array([0.04674978, 0.02814242, 0.06852152, 0.05838899, 0.06132258,
        0.06530342, 0.06696759, 0.04604486, 0.1071576 , 0.06578914,
        0.07347056, 0.07314826, 0.02972068, 0.04886323, 0.06302273,
        0.06289671, 0.04662677, 0.05282358]),
 'rank_test_score': array([ 7,  6, 12, 15,  2, 10,  5,  4, 13, 18, 11, 17,  3,  1,  8,  9, 14,
        16])}

In [10]:
table=pd.DataFrame.from_dict(re) # converting the dictionary format into readable format

In [11]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.596558,0.892115,0.008607,0.006005,mse,auto,best,"{'criterion': 'mse', 'max_features': 'auto', '...",0.726843,0.611288,0.729247,0.729167,0.670979,0.693505,0.046750,7
1,0.064749,0.022305,0.008650,0.006103,mse,auto,random,"{'criterion': 'mse', 'max_features': 'auto', '...",0.692857,0.667965,0.742507,0.705941,0.665882,0.695030,0.028142,6
2,0.057824,0.008402,0.002999,0.002448,mse,sqrt,best,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.689479,0.536126,0.732611,0.630609,0.694386,0.656642,0.068522,12
3,0.050108,0.000706,0.006197,0.000977,mse,sqrt,random,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.641425,0.571571,0.749514,0.642886,0.618269,0.644733,0.058389,15
4,0.049450,0.001484,0.005867,0.003067,mse,log2,best,"{'criterion': 'mse', 'max_features': 'log2', '...",0.802628,0.638024,0.732854,0.642703,0.716899,0.706622,0.061323,2
5,0.223239,0.312129,0.003141,0.004103,mse,log2,random,"{'criterion': 'mse', 'max_features': 'log2', '...",0.719896,0.544745,0.662609,0.724910,0.681350,0.666702,0.065303,10
6,0.176484,0.049720,0.005862,0.005880,mae,auto,best,"{'criterion': 'mae', 'max_features': 'auto', '...",0.725953,0.565240,0.717025,0.723436,0.752898,0.696911,0.066968,5
7,0.129104,0.036760,0.006937,0.011538,mae,auto,random,"{'criterion': 'mae', 'max_features': 'auto', '...",0.655678,0.627556,0.735365,0.733465,0.732625,0.696938,0.046045,4
8,0.088619,0.027723,0.015940,0.017127,mae,sqrt,best,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.725227,0.444973,0.710124,0.726384,0.670398,0.655421,0.107158,13
9,0.103783,0.075003,0.009375,0.012499,mae,sqrt,random,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.671624,0.514189,0.700399,0.668121,0.616739,0.634214,0.065789,18
10,0.094833,0.015295,0.017873,0.014681,mae,log2,best,"{'criterion': 'mae', 'max_features': 'log2', '...",0.726524,0.536909,0.627561,0.696066,0.731620,0.663736,0.073471,11
11,0.124997,0.125385,0.009375,0.007655,mae,log2,random,"{'criterion': 'mae', 'max_features': 'log2', '...",0.583511,0.579785,0.734482,0.716286,0.567487,0.636310,0.073148,17
12,0.009377,0.007656,0.006251,0.007655,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.711152,0.654253,0.720984,0.733963,0.675313,0.699133,0.029721,3
13,0.009375,0.007655,0.009374,0.007654,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.685878,0.633718,0.763213,0.721159,0.761258,0.713045,0.048863,1
14,0.019442,0.007357,0.007596,0.005170,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.743096,0.650353,0.731992,0.699440,0.570813,0.679139,0.063023,8
15,0.004796,0.006008,0.014582,0.009549,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.683358,0.554389,0.740143,0.706316,0.672251,0.671291,0.062897,9
16,0.009376,0.007656,0.006251,0.007656,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.618043,0.598306,0.724729,0.624499,0.680738,0.649263,0.046627,14
17,0.010011,0.008255,0.007451,0.007027,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.639305,0.536064,0.670053,0.675764,0.671266,0.638490,0.052824,16

In [12]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:33
BMI:1
Children:3
Sex Male 0 or 1:1
Smoker Yes 0 or 1:0

In [13]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
#change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[5253.524]

C:\Users\SkillRishi\Anaconda3\lib\site-packages\sklearn\base.py:442: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  "X does not have valid feature names, but"