In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
# As the above dataset contains sex and smoker columns as a categorical value 
# We need to convert that into numerical value using below one hot encoding method.
dataset=pd.get_dummies(dataset,drop_first=True) # Removing the repeated value column

In [5]:
dataset # Once the categorical columns converted into numerical column values

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']] # separating the input values
dep=dataset['charges'] # separating the output values

In [7]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(indep, dep, 
                                                    test_size = 1/3, random_state = 0)

In [8]:
# Data Preprocessing
# converting irrelavant numerical to a relevant numerical values
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
# Consolidating the playable parameters probability and also considering the cross validation
# Considering different portions of a data set as a test and traint set
from sklearn.model_selection import GridSearchCV 
from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['mse','mae','friedman_mse'],
'max_features': ['auto','sqrt','log2'],
'splitter':['best','random']} # Giving all possible HTPs
grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose = 3,n_jobs=-1) 
# refit = True means consider the best result model as a result model
# refit = False means consider the last combination model as a result model
# fitting the model for grid search
grid.fit(X_train, Y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['mse', 'mae', 'friedman_mse'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [10]:
# print best parameter after tuning
print(grid.best_params_)
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

{'criterion': 'friedman_mse', 'max_features': 'auto', 'splitter': 'random'}
The R_score value for best parameter {'criterion': 'friedman_mse', 'max_features': 'auto', 'splitter': 'random'}:

In [11]:
re

{'mean_fit_time': array([0.02187371, 0.0156251 , 0.00624943, 0.00937428, 0.01250072,
        0.00937347, 0.0374979 , 0.02812419, 0.01875067, 0.01249914,
        0.01562424, 0.01562386, 0.00937424, 0.00625024, 0.00625005,
        0.00312567, 0.00312591, 0.00625024]),
 'std_fit_time': array([7.65414951e-03, 2.34863479e-06, 7.65395465e-03, 1.24990463e-02,
        6.25035763e-03, 7.65340974e-03, 7.65374063e-03, 6.24995248e-03,
        6.24883207e-03, 6.24957096e-03, 8.44957597e-07, 1.53331139e-06,
        7.65403274e-03, 7.65494768e-03, 7.65471386e-03, 6.25133514e-03,
        6.25181198e-03, 7.65494758e-03]),
 'mean_score_time': array([0.00312543, 0.        , 0.0062501 , 0.00312529, 0.        ,
        0.00312567, 0.        , 0.00312552, 0.00312443, 0.00312552,
        0.        , 0.00625072, 0.        , 0.        , 0.00312419,
        0.        , 0.        , 0.        ]),
 'std_score_time': array([0.00625086, 0.        , 0.00765477, 0.00625057, 0.        ,
        0.00625134, 0.        , 0.00625105, 0.00624886, 0.00625105,
        0.        , 0.00765553, 0.        , 0.        , 0.00624838,
        0.        , 0.        , 0.        ]),
 'param_criterion': masked_array(data=['mse', 'mse', 'mse', 'mse', 'mse', 'mse', 'mae', 'mae',
                    'mae', 'mae', 'mae', 'mae', 'friedman_mse',
                    'friedman_mse', 'friedman_mse', 'friedman_mse',
                    'friedman_mse', 'friedman_mse'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False],
        fill_value='?',
             dtype=object),
 'param_max_features': masked_array(data=['auto', 'auto', 'sqrt', 'sqrt', 'log2', 'log2', 'auto',
                    'auto', 'sqrt', 'sqrt', 'log2', 'log2', 'auto', 'auto',
                    'sqrt', 'sqrt', 'log2', 'log2'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False],
        fill_value='?',
             dtype=object),
 'param_splitter': masked_array(data=['best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random', 'best', 'random'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False],
        fill_value='?',
             dtype=object),
 'params': [{'criterion': 'mse', 'max_features': 'auto', 'splitter': 'best'},
  {'criterion': 'mse', 'max_features': 'auto', 'splitter': 'random'},
  {'criterion': 'mse', 'max_features': 'sqrt', 'splitter': 'best'},
  {'criterion': 'mse', 'max_features': 'sqrt', 'splitter': 'random'},
  {'criterion': 'mse', 'max_features': 'log2', 'splitter': 'best'},
  {'criterion': 'mse', 'max_features': 'log2', 'splitter': 'random'},
  {'criterion': 'mae', 'max_features': 'auto', 'splitter': 'best'},
  {'criterion': 'mae', 'max_features': 'auto', 'splitter': 'random'},
  {'criterion': 'mae', 'max_features': 'sqrt', 'splitter': 'best'},
  {'criterion': 'mae', 'max_features': 'sqrt', 'splitter': 'random'},
  {'criterion': 'mae', 'max_features': 'log2', 'splitter': 'best'},
  {'criterion': 'mae', 'max_features': 'log2', 'splitter': 'random'},
  {'criterion': 'friedman_mse', 'max_features': 'auto', 'splitter': 'best'},
  {'criterion': 'friedman_mse', 'max_features': 'auto', 'splitter': 'random'},
  {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'splitter': 'best'},
  {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'splitter': 'random'},
  {'criterion': 'friedman_mse', 'max_features': 'log2', 'splitter': 'best'},
  {'criterion': 'friedman_mse', 'max_features': 'log2', 'splitter': 'random'}],
 'split0_test_score': array([0.67965268, 0.64776803, 0.59568054, 0.68401384, 0.66598191,
        0.51570231, 0.65675353, 0.59324449, 0.58048538, 0.66143454,
        0.76143292, 0.50409345, 0.71707067, 0.69462178, 0.59121193,
        0.5172782 , 0.03617944, 0.74353097]),
 'split1_test_score': array([0.47730816, 0.57791964, 0.59490384, 0.47655204, 0.57968561,
        0.47124792, 0.52877481, 0.68888212, 0.71354343, 0.59791634,
        0.68448161, 0.31252267, 0.48579411, 0.68427389, 0.58787436,
        0.52697679, 0.56664491, 0.51829471]),
 'split2_test_score': array([0.74448148, 0.67951359, 0.63468716, 0.60518163, 0.67215505,
        0.57003579, 0.69470217, 0.69448222, 0.66238977, 0.60787136,
        0.33837636, 0.68615895, 0.76353047, 0.76337615, 0.72585038,
        0.63620007, 0.61084734, 0.54517528]),
 'split3_test_score': array([0.61065294, 0.58693064, 0.57894669, 0.53105723, 0.64953832,
        0.62267964, 0.59968171, 0.59261733, 0.50906238, 0.55629811,
        0.40824278, 0.58506272, 0.62752068, 0.48895042, 0.65989411,
        0.65284377, 0.6020563 , 0.42245297]),
 'split4_test_score': array([0.66409516, 0.63657909, 0.48174822, 0.52821024, 0.62195607,
        0.54543607, 0.65182817, 0.66025063, 0.57800484, 0.56910908,
        0.57799367, 0.6543542 , 0.66013169, 0.69432169, 0.49050208,
        0.53745148, 0.58750786, 0.53379296]),
 'mean_test_score': array([0.63523809, 0.6257422 , 0.57719329, 0.56500299, 0.63786339,
        0.54502034, 0.62634808, 0.64589536, 0.60869716, 0.59852589,
        0.55410547, 0.5484384 , 0.65080953, 0.66510879, 0.61106657,
        0.57415006, 0.48064717, 0.55264938]),
 'std_test_score': array([0.08976168, 0.03817662, 0.05113477, 0.07225994, 0.03388383,
        0.05090939, 0.0574067 , 0.04477785, 0.07147118, 0.03658891,
        0.16022998, 0.13352839, 0.09482184, 0.0924986 , 0.07877479,
        0.05805069, 0.2227369 , 0.10486044]),
 'rank_test_score': array([ 5,  7, 11, 13,  4, 17,  6,  3,  9, 10, 14, 16,  2,  1,  8, 12, 18,
        15])}

In [12]:
table=pd.DataFrame.from_dict(re) # converting the dictionary format into readable format

In [13]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.021874,7.654150e-03,0.003125,0.006251,mse,auto,best,"{'criterion': 'mse', 'max_features': 'auto', '...",0.679653,0.477308,0.744481,0.610653,0.664095,0.635238,0.089762,5
1,0.015625,2.348635e-06,0.000000,0.000000,mse,auto,random,"{'criterion': 'mse', 'max_features': 'auto', '...",0.647768,0.577920,0.679514,0.586931,0.636579,0.625742,0.038177,7
2,0.006249,7.653955e-03,0.006250,0.007655,mse,sqrt,best,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.595681,0.594904,0.634687,0.578947,0.481748,0.577193,0.051135,11
3,0.009374,1.249905e-02,0.003125,0.006251,mse,sqrt,random,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.684014,0.476552,0.605182,0.531057,0.528210,0.565003,0.072260,13
4,0.012501,6.250358e-03,0.000000,0.000000,mse,log2,best,"{'criterion': 'mse', 'max_features': 'log2', '...",0.665982,0.579686,0.672155,0.649538,0.621956,0.637863,0.033884,4
5,0.009373,7.653410e-03,0.003126,0.006251,mse,log2,random,"{'criterion': 'mse', 'max_features': 'log2', '...",0.515702,0.471248,0.570036,0.622680,0.545436,0.545020,0.050909,17
6,0.037498,7.653741e-03,0.000000,0.000000,mae,auto,best,"{'criterion': 'mae', 'max_features': 'auto', '...",0.656754,0.528775,0.694702,0.599682,0.651828,0.626348,0.057407,6
7,0.028124,6.249952e-03,0.003126,0.006251,mae,auto,random,"{'criterion': 'mae', 'max_features': 'auto', '...",0.593244,0.688882,0.694482,0.592617,0.660251,0.645895,0.044778,3
8,0.018751,6.248832e-03,0.003124,0.006249,mae,sqrt,best,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.580485,0.713543,0.662390,0.509062,0.578005,0.608697,0.071471,9
9,0.012499,6.249571e-03,0.003126,0.006251,mae,sqrt,random,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.661435,0.597916,0.607871,0.556298,0.569109,0.598526,0.036589,10
10,0.015624,8.449576e-07,0.000000,0.000000,mae,log2,best,"{'criterion': 'mae', 'max_features': 'log2', '...",0.761433,0.684482,0.338376,0.408243,0.577994,0.554105,0.160230,14
11,0.015624,1.533311e-06,0.006251,0.007656,mae,log2,random,"{'criterion': 'mae', 'max_features': 'log2', '...",0.504093,0.312523,0.686159,0.585063,0.654354,0.548438,0.133528,16
12,0.009374,7.654033e-03,0.000000,0.000000,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.717071,0.485794,0.763530,0.627521,0.660132,0.650810,0.094822,2
13,0.006250,7.654948e-03,0.000000,0.000000,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.694622,0.684274,0.763376,0.488950,0.694322,0.665109,0.092499,1
14,0.006250,7.654714e-03,0.003124,0.006248,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.591212,0.587874,0.725850,0.659894,0.490502,0.611067,0.078775,8
15,0.003126,6.251335e-03,0.000000,0.000000,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.517278,0.526977,0.636200,0.652844,0.537451,0.574150,0.058051,12
16,0.003126,6.251812e-03,0.000000,0.000000,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.036179,0.566645,0.610847,0.602056,0.587508,0.480647,0.222737,18
17,0.006250,7.654948e-03,0.000000,0.000000,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.743531,0.518295,0.545175,0.422453,0.533793,0.552649,0.104860,15

In [14]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:56
BMI:23
Children:1
Sex Male 0 or 1:1
Smoker Yes 0 or 1:1

In [15]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
#change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[15230.32405]